platform :ios, '9.0'
#inhibit_all_warnings!
use_frameworks!

target 'NaturalVoice_Example' do
  pod 'NaturalVoice', :path => '../'

  target 'NaturalVoice_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
